### PR TITLE
Update google_colab_demo.ipynb with go 1.23.1

### PR DESCRIPTION
**Pull request by aaronwe**
The Colab demo currently fails in the Shining cell with 

 go: downloading github.com/ajstarks/svgo v0.0.0-20211024235047-1546f124cd8b
 go: github.com/janpfeifer/gonb@v0.10.3 requires go >= 1.23 (running go 1.22.2)

Updated the import cell to wget 'https://go.dev/dl/go1.23.1.linux-amd64.tar.gz'

### CODE REVIEW

**Comment by janpfeifer** [comment]
DId you manage to make it work ? This is awesome!

**Comment by aaronwe** [comment]
Yeah, reloaded it with the new version and it seems happy. First few cells in the demo all ran fine. I didn't run through the entire notebook but it looks good.

Here's my fork: https://colab.research.google.com/drive/1kZYOWZ6fseZZLlP2O7S88TqxwdUQmulq?usp=sharing

**Comment by aaronwe** [comment]
FYI, cell 5 in the notebook seems to fail still but I don't think that's related to the Go version. I get:

> Cell[5]: Line 21 ./main.go:107:46: cannot use true (untyped bool constant) as types.Bool value in struct literal
> Cell[5]: Line 25 ./main.go:111:17: cannot use true (untyped bool constant) as types.Bool value in struct literal

**Comment by janpfeifer** [comment]
I wonder what could be causing errors ... But we can figure it out later.

I actually thought the Google Colab was no longer working --- every now and then things seems to change and the hack to make it run another kernel stops working. 

Thanks for fixing it!

**Comment by janpfeifer** [comment]
Found it ... something must have changed in the go-echarts, replacing `types.Bool(true)` by `opts.Bool(true)` seems to make it work though.

**Pull request merged**
