### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by bagel897**
# The problem
When gonb runs into errors, it generates HTML error reports. These are great for a jupyter notebook, but don't render in [nbmake](https://github.com/treebeardtech/nbmake)
# The solution
Add an option to print out raw error messages instead of html reports, set by a command line flag. This works inside nbmake.
image
image

### CODE REVIEW

**Comment by janpfeifer** [comment]
Thanks @bagel897 , this looks really great! Having it work well `nbmake` facilitates testing -- I have to start using, it also for GoNB (lots of things I didn't test because were not easy to).

A few suggestions (all very small "nit-picks"), I hope you don't mind. 

- In `goexec/errorcontext.go`, the small functions `max`, `min` and `inBetween` are all used in the new `errorLine.go`, so they may just be moved there.
- `errorcontext.go` became really small. What do you think about merging it with `error.go` ? Either way is good, just something to think about.
- Because `klog` injects many other flags, when reading the output of a `gonb --help` (or `go run . --help`), it's hard for someone to understand that `--raw_error` is about the GoNB cell execution error. Maybe comment that on the comment of the flag ? Something like (suggestion) "When GoNB executes cells, force raw text errors instead of HTML errors, which facilitates command line testing of notebooks" ?

Let me know if you would like to change them before merging (or if you disagree), or I'll just merge your PR as is do the small changes later (likely on Monday morning)

cheers, and thanks!!

**Comment by bagel897** [comment]
1. Sounds good!
2. errorcontext.go still has the HTML template. But I understand combining the two files, it'd make it simpler. Alternatively, I can move the HTML report part back into errorcontext.go
3. Ill do that as well

I'll do the changes monday morning, is that alright?

**Comment by janpfeifer** [comment]
That's perfect, thanks again Ellen.

**Comment by bagel897** [comment]
Thanks for the feedback!
1. Done
2. I renamed it to htmlerror and moved all the HTML code back into the file. This leaves it over 100 lines, which should be good. Alternatively, we could move all the error files into their own error module, would that work better?
3. I updated the help flag

**Review by janpfeifer — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
